function AlgInfo = getAlgInfo()

	AlgInfo = struct( ...
	...
		'X2Qual', 				1,	... % If TRUE, tune D1 such that X2 is nearly orthogonal
		'X2tune', 				10^5, ...
		'Iter',					[], ...
		...
		'D1', ...
			struct( ...
				'Swarm',		[], ... % The number of swarm size of Core
				'Iter',			[], ... % The number of total iterations for tuning D1
				'qGB',			[], ... % The number of exchanged column with global best
				'qLB',			[], ... % The number of exchanged column with local best
				'qRC',			[] 	... % The number of exchanged column randomly
			), ...
		'D1f2', ...
			struct( ...
				'Swarm',		[], ... % The number of swarm size of Core
				'Iter',			[], ... % The number of total iterations for tuning D1
				'qGB',			[], ... % The number of exchanged column with global best
				'qLB',			[], ... % The number of exchanged column with local best
				'qRC',			[] 	... % The number of exchanged column randomly
			), ...
		'D1f3', ...
			struct( ...
				'Swarm',		[], ... % The number of swarm size of Core
				'Iter',			[], ... % The number of total iterations for tuning D1
				'qGB',			[], ... % The number of exchanged column with global best
				'qLB',			[], ... % The number of exchanged column with local best
				'qRC',			[] 	... % The number of exchanged column randomly
			), ...
		...
		'D3', ...
			struct( ...
				'Swarm',		[], ... % The number of swarm size of D3
				'Iter',			[], ... % The number of total iterations for tuning D3
				'qGB',			[], ... % The number of exchanged column with global best
				'qLB',			[], ... % The number of exchanged column with local best
				'qRC',			[] 	... % The number of exchanged column randomly
			), ...
		'save', ...
			struct( ...
				'Overall',	[], ...  
				'D3Res',		[] 	... 
			) ...		
	);
